import {STORAGE_KEY,uid,today,money,monthLabel,dateLabel,FREQUENCIES,initialState,parseAmount,validDate,shiftMonth,occurrence,processRules,summary,budgetUsage,validateState,loadState,saveState,transactionsCsv} from './model.js';

const $=(s,root=document)=>root.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-8H9v8H4a1 1 0 0 1-1-1z"/>',overview:'<path d="M12 3v9h9A9 9 0 1 1 12 3Z"/><path d="M16 3a8 8 0 0 1 5 5h-5z"/>',budgets:'<rect x="3" y="13" width="4" height="8" rx="1"/><rect x="10" y="4" width="4" height="17" rx="1"/><rect x="17" y="9" width="4" height="12" rx="1"/>',settings:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>'};
const svg=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
let state,blocked=false;
try{state=loadState();}catch{blocked=true;state=initialState();}
let month=today().slice(0,7),page='home',overviewType='expense',period='month',chartMode='bar',filter={query:'',type:'all',category:'all',label:'all',from:'',to:''},showFilters=false;
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4000);}
function applyTheme(){const pref=state.settings.theme;document.documentElement.dataset.theme=pref==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):pref;}
function commit(mutator){
  if(blocked){toast('Restore a backup or reset unreadable data in Settings before making changes.');return false;}
  const next=structuredClone(state);
  try{mutator(next);saveState(next);state=next;applyTheme();render();return true;}catch(e){toast(e.name==='QuotaExceededError'?'Storage is full. Export a backup before freeing space.':`Could not save: ${e.message}`);return false;}
}
function catchUp(){if(blocked)return;const next=structuredClone(state);const n=processRules(next);if(n||JSON.stringify(next.rules)!==JSON.stringify(state.rules)){try{saveState(next);state=next;if(n)toast(`${n} recurring ${n===1?'transaction':'transactions'} added.`);}catch{toast('Recurring entries could not be saved. Please export a backup.');}}}
catchUp();applyTheme();
function cat(id){return state.categories.find(c=>c.id===id);}
function categoryIcon(c){return `<span class="category-icon" style="background:${c.color}20">${esc(c.icon)}</span>`;}
function monthControl(){return `<div class="month-switch"><button class="icon-btn" data-action="prev-month" aria-label="Previous month">‹</button><input class="month-input" aria-label="Selected month" id="month" type="month" min="1900-01" max="2200-12" value="${month}"><button class="icon-btn" data-action="next-month" aria-label="Next month">›</button></div>`;}
function head(title,subtitle=''){return `<div class="page-head"><div>${subtitle?`<div class="eyebrow">${subtitle}</div>`:''}<h1>${title}</h1></div>${page==='settings'?'':monthControl()}</div>`;}
const actual=()=>state.transactions.filter(t=>t.date<=today());
function empty(title,description,action='',button=''){return `<div class="empty"><div class="empty-icon">◈</div><h3>${title}</h3><p>${description}</p>${action?`<button class="btn secondary" data-action="${action}">${button}</button>`:''}</div>`;}
function historyRows(){return actual().filter(t=>{
  const c=cat(t.categoryId);const query=[t.description,c.name,...t.labelIds.map(id=>state.labels.find(l=>l.id===id)?.name||'')].join(' ').toLowerCase();
  return (filter.from||filter.to?(!filter.from||t.date>=filter.from)&&(!filter.to||t.date<=filter.to):t.date.startsWith(month))&&(filter.type==='all'||t.type===filter.type)&&(filter.category==='all'||t.categoryId===filter.category)&&(filter.label==='all'||t.labelIds.includes(filter.label))&&query.includes(filter.query.toLowerCase());
}).sort((a,b)=>b.date.localeCompare(a.date));}
function transactionRow(t){const c=cat(t.categoryId);return `<button class="transaction" data-action="edit-transaction" data-id="${esc(t.id)}">${categoryIcon(c)}<span class="transaction-copy"><strong>${esc(c.name)}</strong><p>${esc(t.description||t.labelIds.map(id=>state.labels.find(l=>l.id===id)?.name).join(' · ')||dateLabel(t.date))}</p></span><span class="transaction-amount ${t.type==='income'?'green':''}">${t.type==='expense'?'−':'+'}${money(t.amount)}${t.excluded||t.ruleId?`<small>${t.excluded?'Excluded':FREQUENCIES[state.rules.find(r=>r.id===t.ruleId)?.frequency]||'Recurring'}</small>`:''}</span></button>`;}
function historyHtml(){const rows=historyRows();let out='',current='';for(const t of rows){if(t.date!==current){if(current)out+='</div>';current=t.date;const day=rows.filter(x=>x.date===current);const s=summary(day);out+=`<div class="day-header"><span>${current===today()?'Today':dateLabel(current)}</span><span>${money(s.income-s.expense)}</span></div><div class="transaction-list">`;}out+=transactionRow(t);}return out+(current?'</div>':empty('No transactions yet','Add a transaction, or adjust your filters.','add','Add transaction'));}
function filtersHtml(){return `<div class="filter-bar"><div class="search">${svg('search')}<input id="search" aria-label="Search transactions" placeholder="Search transactions" value="${esc(filter.query)}" type="search"></div><button class="filter-button" data-action="toggle-filters" aria-expanded="${showFilters}">Filters${Object.entries(filter).some(([k,v])=>k!=='query'&&v!=='all'&&v!=='')?' ·':''}</button></div>${showFilters?`<div class="card filters"><label>Type<select id="filter-type"><option value="all">Income & expenses</option><option value="expense" ${filter.type==='expense'?'selected':''}>Expenses</option><option value="income" ${filter.type==='income'?'selected':''}>Income</option></select></label><label>Category<select id="filter-category"><option value="all">All categories</option>${state.categories.map(c=>`<option value="${esc(c.id)}" ${filter.category===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Label<select id="filter-label"><option value="all">All labels</option>${state.labels.map(l=>`<option value="${esc(l.id)}" ${filter.label===l.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select></label><label>From<input id="filter-from" type="date" min="1900-01-01" max="2200-12-31" value="${filter.from}"></label><label>To<input id="filter-to" type="date" min="1900-01-01" max="2200-12-31" value="${filter.to}"></label><button class="text-btn" data-action="clear-filters">Clear filters</button></div>`:''}`;}
function cashChart(){const months=Array.from({length:6},(_,i)=>shiftMonth(month,i-5));const vals=months.map(m=>summary(actual().filter(t=>t.date.startsWith(m))));const max=Math.max(100,...vals.flatMap(v=>[v.income,v.expense]));const top=15,bottom=130,height=115;
  let content=[0,.5,1].map(n=>`<line x1="0" y1="${bottom-height*n}" x2="420" y2="${bottom-height*n}" stroke="currentColor" opacity=".16" stroke-dasharray="4 5"/><text x="0" y="${bottom-height*n-5}" fill="currentColor" font-size="10">${n?money(Math.round(max*n)).replace(/\.00$/,''):'0'}</text>`).join('');
  const xs=months.map((m,i)=>42+i*66);
  if(chartMode==='line'){for(const [key,color] of [['income','#2563eb'],['expense','#7ca6f7']])content+=`<polyline points="${vals.map((v,i)=>`${xs[i]+13},${bottom-height*v[key]/max}`).join(' ')}" fill="none" stroke="${color}" stroke-width="3"/>`;}
  else vals.forEach((v,i)=>{content+=`<rect x="${xs[i]}" y="${bottom-height*v.income/max}" width="12" height="${height*v.income/max}" rx="3" fill="#2563eb"/><rect x="${xs[i]+15}" y="${bottom-height*v.expense/max}" width="12" height="${height*v.expense/max}" rx="3" fill="#7ca6f7"/>`;});
  content+=months.map((m,i)=>`<text x="${xs[i]+13}" y="152" text-anchor="middle" fill="currentColor" font-size="11" ${m===month?'font-weight="700"':''}>${new Date(m+'-01T12:00:00').toLocaleDateString('en',{month:'short'})}</text>`).join('');
  return `<div class="chart-wrap"><svg class="chart-svg" viewBox="0 0 420 165" role="img" aria-label="Income and expenses for six months ending ${esc(monthLabel(month))}"><title>${months.map((m,i)=>`${monthLabel(m)}: income ${money(vals[i].income)}, expenses ${money(vals[i].expense)}`).join('; ')}</title>${content}</svg></div><div class="legend"><span><i></i>Income</span><span><i class="expense"></i>Expenses</span></div>`;
}
function budgetCard(b){const used=budgetUsage(state,b,month);const pct=used/b.amount*100;const remaining=b.amount-used;const end=new Date(`${shiftMonth(month,1)}-01T12:00:00Z`);end.setUTCDate(0);const endDate=end.toISOString().slice(0,10);const days=month===today().slice(0,7)?Math.max(1,end.getUTCDate()-Number(today().slice(-2))+1):end.getUTCDate();const active=month>=b.startDate.slice(0,7);
  return `<div class="card budget-card"><div class="budget-top"><strong>${esc(b.name)}</strong><button class="text-btn" data-action="edit-budget" data-id="${esc(b.id)}">Edit</button></div><div class="budget-numbers"><strong>${money(used)}</strong><span class="muted small">of ${money(b.amount)}</span></div><div class="progress ${pct>=100?'over':pct>=80?'warning':''}" role="progressbar" aria-label="${esc(b.name)} spent" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.min(100,Math.round(pct))}" aria-valuetext="${pct.toFixed(1)} percent spent"><span style="width:${Math.min(100,pct)}%"></span></div><div class="budget-foot"><span class="${pct>=100?'red':''}">${!active?'Starts '+dateLabel(b.startDate):remaining<0?money(-remaining)+' over':money(remaining)+' left'}</span><span>${pct.toFixed(0)}% used</span></div>${active&&month===today().slice(0,7)&&remaining>0?`<p class="muted small spacer">${money(Math.floor(remaining/days))} / day · ${days} ${days===1?'day':'days'} left</p>`:''}</div>`;
}
function upcoming(){const list=state.transactions.filter(t=>t.date>today()).map(t=>({...t,existing:true}));for(const r of state.rules.filter(r=>r.active)){for(let i=r.nextIndex;i<r.nextIndex+100;i++){const date=occurrence(r,i);if(date>`${month}-31`||(r.endDate&&date>r.endDate))break;if(date>today()&&date.startsWith(month))list.push({...r.template,id:r.id,date,ruleId:r.id,existing:false});}}return list.filter(t=>t.date.startsWith(month)).sort((a,b)=>a.date.localeCompare(b.date));}
function home(){const s=summary(actual().filter(t=>t.date.startsWith(month)));const up=upcoming();return `${head('Your everyday','OVERVIEW')}<div class="dashboard-top"><div class="hero"><div class="eyebrow">NET CASH FLOW · ${esc(new Date(month+'-01').toLocaleDateString('en',{month:'short'})).toUpperCase()}</div><div class="hero-amount">${money(s.income-s.expense)}</div><div class="hero-stats"><div class="hero-stat"><small><span class="dot">+</span>Income</small><strong>${money(s.income)}</strong></div><div class="hero-stat"><small><span class="dot">−</span>Expenses</small><strong>${money(s.expense)}</strong></div></div></div><div class="card chart-card"><div class="section-head"><h2>Cash flow</h2><span class="muted small">Past 6 months</span></div>${cashChart()}</div></div><section class="section"><div class="section-head"><h2>Monthly budgets</h2><a class="text-btn" href="#budgets">${state.budgets.length?'View all':'Set a budget'}</a></div>${state.budgets.length?`<div class="budget-grid">${state.budgets.slice(0,2).map(budgetCard).join('')}</div>`:`<div class="card">${empty('A little room to plan','Set a monthly limit and see how much you have left.','add-budget','Set a budget')}</div>`}</section>${up.length?`<button class="card scheduled" data-action="scheduled"><span class="category-icon">◷</span><span><strong>Scheduled this month</strong><small class="muted">${up.length} upcoming ${up.length===1?'transaction':'transactions'}</small></span><span class="scheduled-total">${money(summary(up).income-summary(up).expense)}</span></button>`:''}<section class="section"><div class="section-head"><h2>Transactions</h2><button class="text-btn" data-action="export-filtered">Export CSV</button></div>${filtersHtml()}<div id="history">${historyHtml()}</div></section>`;}
function periodRows(selected=month){const all=actual().filter(t=>!t.excluded&&t.type===overviewType);if(period==='all')return all;if(period==='year')return all.filter(t=>t.date.startsWith(selected.slice(0,4)));if(period==='week'){const d=new Date(selected===today().slice(0,7)?today()+'T12:00:00Z':selected+'-01T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);const from=d.toISOString().slice(0,10);d.setUTCDate(d.getUTCDate()+6);const to=d.toISOString().slice(0,10);return all.filter(t=>t.date>=from&&t.date<=to);}return all.filter(t=>t.date.startsWith(selected));}
function overview(){const rows=periodRows();const total=rows.reduce((s,t)=>s+t.amount,0);let previousRows;if(period==='week'){const d=new Date((month===today().slice(0,7)?today():month+'-01')+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7-7);const from=d.toISOString().slice(0,10);d.setUTCDate(d.getUTCDate()+6);const to=d.toISOString().slice(0,10);previousRows=actual().filter(t=>!t.excluded&&t.type===overviewType&&t.date>=from&&t.date<=to);}else previousRows=periodRows(shiftMonth(month,period==='year'?-12:-1));const previous=previousRows.reduce((s,t)=>s+t.amount,0);const delta=previous?(total-previous)/previous*100:null;
  const categories=state.categories.filter(c=>c.type===overviewType).map(c=>({...c,total:rows.filter(t=>t.categoryId===c.id).reduce((s,t)=>s+t.amount,0),count:rows.filter(t=>t.categoryId===c.id).length})).filter(c=>c.total).sort((a,b)=>b.total-a.total);
  let start=0;const gradient=categories.map(c=>{const end=start+c.total/total*100;const segment=`${c.color} ${start}% ${end}%`;start=end;return segment;}).join(',');
  return `${head('The bigger picture','INSIGHTS')}<div class="overview-controls"><div class="segmented"><button data-action="overview-type" data-id="expense" class="${overviewType==='expense'?'selected':''}">Expenses</button><button data-action="overview-type" data-id="income" class="${overviewType==='income'?'selected':''}">Income</button></div><select id="period" aria-label="Overview period">${[['week','Week'],['month','Month'],['year','Year'],['all','All time']].map(([id,label])=>`<option value="${id}" ${period===id?'selected':''}>${label}</option>`).join('')}</select><select id="chart-mode" aria-label="Trend chart style"><option value="bar" ${chartMode==='bar'?'selected':''}>Bar chart</option><option value="line" ${chartMode==='line'?'selected':''}>Line chart</option></select></div><div class="overview-layout"><div class="card"><div class="eyebrow">${overviewType==='expense'?'TOTAL SPENDING':'TOTAL INCOME'}</div><div class="overview-total">${money(total)}</div><p class="muted small">${period==='week'?'Week containing '+(month===today().slice(0,7)?dateLabel(today()):dateLabel(month+'-01')):period==='year'?month.slice(0,4):period==='all'?'All recorded transactions':monthLabel(month)}</p>${period!=='all'?`<p class="small spacer ${delta!==null&&(overviewType==='expense'?delta<0:delta>0)?'green':'muted'}">${delta===null?'No previous-period total to compare':`${delta>=0?'↑':'↓'} ${Math.abs(delta).toFixed(1)}% vs. previous period`}</p>`:''}<div class="donut" style="background:${total?`conic-gradient(${gradient})`:'var(--line)'}" role="img" aria-label="${overviewType} by category"><div class="donut-hole"><strong>${categories.length}</strong><span>${categories.length===1?'category':'categories'}</span></div></div>${!total?empty('A fresh start','Your category breakdown will appear as you add transactions.'):categories.map(c=>`<div class="category-breakdown">${categoryIcon(c)}<div><strong>${esc(c.name)}</strong><small>${c.count} ${c.count===1?'transaction':'transactions'}</small></div><div class="right"><strong>${money(c.total)}</strong><small>${(c.total/total*100).toFixed(1)}%</small></div></div>`).join('')}</div><div class="card"><div class="section-head"><h2>Income vs. expenses</h2><span class="muted small">6 months</span></div>${cashChart()}<p class="muted small spacer">Excludes upcoming transactions and entries marked “Exclude from overview”.</p></div></div>`;
}
function budgets(){const active=state.budgets.filter(b=>month>=b.startDate.slice(0,7));const over=active.filter(b=>budgetUsage(state,b,month)>=b.amount);return `${head('Monthly budgets','YOUR SPENDING PLAN')}<div class="section-head"><p class="muted small">Your limits reset each calendar month.</p><button class="text-btn" data-action="add-budget">+ New budget</button></div>${over.length?`<div class="alert">${over.map(b=>esc(b.name)).join(', ')}: budget limit reached. Review your spending below.</div>`:''}${state.budgets.length?`<div class="budget-grid">${state.budgets.map(budgetCard).join('')}</div>`:`<div class="card">${empty('Give your month a plan','Create an overall budget or a limit for specific categories.','add-budget','Create a budget')}</div>`}`;}
function settings(){return `${head('Your preferences','SETTINGS')}<div class="overview-layout"><div><div class="card settings-group"><button class="setting-row" data-action="manage-categories"><span><strong>Categories</strong><small>Organise income and expenses</small></span><span class="muted">${state.categories.filter(c=>!c.archived).length} ›</span></button><button class="setting-row" data-action="manage-labels"><span><strong>Labels</strong><small>Add context to your transactions</small></span><span class="muted">${state.labels.length} ›</span></button><button class="setting-row" data-action="manage-rules"><span><strong>Recurring transactions</strong><small>Manage automatic entries</small></span><span class="muted">${state.rules.filter(r=>r.active).length} active ›</span></button><label class="setting-row"><span><strong>Appearance</strong><small>Make it feel like yours</small></span><select id="theme" aria-label="Appearance">${['system','light','dark'].map(t=>`<option value="${t}" ${state.settings.theme===t?'selected':''}>${t[0].toUpperCase()+t.slice(1)}</option>`).join('')}</select></label></div><div class="card settings-group"><div class="section-head"><h2>Your data</h2><span class="local-badge">◇ On this device</span></div><button class="setting-row" data-action="export-all"><span><strong>Export transactions</strong><small>Download a CSV for your spreadsheet</small></span><span class="muted">↓</span></button><button class="setting-row" data-action="backup"><span><strong>Back up everything</strong><small>Transactions, budgets, categories and settings</small></span><span class="muted">↓</span></button><button class="setting-row" data-action="restore"><span><strong>Restore a backup</strong><small>Replace current data with a JSON backup</small></span><span class="muted">↑</span></button><button class="setting-row" data-action="reset"><span><strong class="red">Reset all data</strong><small>Export a backup before clearing your records</small></span><span class="muted">×</span></button></div></div><div class="settings-info"><h2 class="spacer">A personal space</h2><p class="spacer">${state.transactions.length} transactions · SGD only</p><p>Your records are saved in this browser on this device. They are never sent to GitHub or any server.</p><p>Clearing browser data can remove your records. Download a JSON backup regularly; you can restore it on another device. CSV exports contain transactions only.</p><p>Recurring entries are added when you open the app. Upcoming entries stay separate from your actual spending.</p><h2 class="spacer">Keep it close</h2><p class="spacer">On iPhone, open in Safari, tap Share, then Add to Home Screen. On Android, use your browser’s Install app or Add to Home screen option.</p><p>The app works offline after your first visit.</p><p>Everyday · version 1.1</p></div></div>`;}
function render(){page=['home','overview','budgets','settings'].includes(location.hash.slice(1))?location.hash.slice(1):'home';$('.bottom-nav').innerHTML=[['home','Home'],['overview','Overview'],['budgets','Budgets'],['settings','Settings']].map(([id,name])=>`<a class="nav-link ${page===id?'active':''}" href="#${id}" ${page===id?'aria-current="page"':''}>${svg(id)}${name}</a>`).join('');$('#app').innerHTML=(blocked?'<div class="alert">Saved data could not be read. Your original data has been preserved. Use Settings to download the original data, restore a backup or reset.</div>':'')+({home,overview,budgets,settings}[page]());}
function openDialog(title,body){$('#editor').classList.remove('transaction-editor');$('#editor').style.removeProperty('--entry-height');$('#dialog-content').innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="icon-btn" data-action="close" aria-label="Close dialog">×</button></div><div class="dialog-body">${body}</div>`;if(!$('#editor').open)$('#editor').showModal();}
function closeDialog(){ $('#editor').close(); }
function error(message){const el=$('#form-error');if(el){el.textContent=message;el.scrollIntoView({block:'nearest'});}else toast(message);}
function labelChips(selected){return `<div class="chips" id="label-chips">${state.labels.map(l=>`<button type="button" class="chip ${selected.includes(l.id)?'selected':''}" aria-pressed="${selected.includes(l.id)}" data-action="toggle-chip" data-id="${esc(l.id)}">${esc(l.name)}</button>`).join('')}<button type="button" class="chip" data-action="quick-label">+ Label</button></div>`;}
function categoryPicker(type,selected){return state.categories.filter(c=>c.type===type&&(!c.archived||c.id===selected)).map(c=>`<button type="button" class="category-choice ${c.id===selected?'selected':''}" aria-pressed="${c.id===selected}" data-action="select-category" data-id="${esc(c.id)}">${categoryIcon(c)}<span>${esc(c.name)}</span></button>`).join('');}
function transactionPanel(mode){
  const form=$('#transaction-form');if(!form)return;
  form.dataset.panel=mode;
  for(const [selector,key] of [['#category-panel','categories'],['#calculator-slot','keypad'],['#transaction-options','options']])$(selector).hidden=mode!==key;
  const c=cat($('#category-id').value);
  $('#selected-category').innerHTML=c?`${categoryIcon(c)}<span>${esc(c.name)}</span><span class="category-chevron">⌄</span>`:'<span class="category-icon">◈</span><span>Select category</span><span class="category-chevron">⌄</span>';
  $('#selected-category').setAttribute('aria-expanded',String(mode==='categories'));
}
function transactionDialog(id){
  const t=id?state.transactions.find(t=>t.id===id):null;if(id&&!t)return;
  const type=t?.type||'expense';
  openDialog(t?'Edit transaction':'Add transaction',`<form id="transaction-form" data-id="${esc(id||'')}">
    <input type="hidden" id="transaction-type" value="${type}"><input type="hidden" id="category-id" value="${esc(t?.categoryId||'')}">
    <div class="entry-hero"><button type="button" id="selected-category" data-action="choose-category" aria-label="Choose category"></button><div class="amount-field"><input id="amount" aria-label="Amount or calculation in SGD" inputmode="none" autocomplete="off" placeholder="0" value="${t?(t.amount/100).toFixed(2):''}" required><span>SGD</span><button type="button" class="calculate-button" data-action="calc-key" data-id="=" aria-label="Calculate amount">=</button></div></div>
    <div class="entry-note"><textarea id="description" aria-label="Transaction description" maxlength="1000" placeholder="Describe your transaction" rows="1">${esc(t?.description||'')}</textarea>${labelChips(t?.labelIds||[])}</div>
    <div class="entry-date-row"><label class="date-pill"><span aria-hidden="true">▦</span><input id="transaction-date" aria-label="Transaction date" type="date" min="1900-01-01" max="2200-12-31" value="${t?.date||today()}" required></label>${t?.ruleId?'<span class="repeat-pill recurring-note">↻ Recurring entry</span>':`<label class="repeat-pill"><span aria-hidden="true">↻</span><select id="frequency" aria-label="Repeat frequency">${Object.entries(FREQUENCIES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label>`}</div>
    <div class="entry-panel"><section id="category-panel"><h3>Select category</h3><div class="category-picker" id="category-picker">${categoryPicker(type,t?.categoryId)}</div></section><div id="calculator-slot" hidden><div class="keypad">${['1','2','3','÷','4','5','6','×','7','8','9','−','.','0','⌫','+'].map(k=>`<button type="button" data-action="calc-key" data-id="${k}" aria-label="${k==='⌫'?'Backspace':k}">${k}</button>`).join('')}</div></div><section id="transaction-options" hidden><h3>Transaction options</h3><label class="checkbox"><input id="excluded" type="checkbox" ${t?.excluded?'checked':''}>Exclude from overview and budgets</label>${t?.ruleId?'<p class="muted small spacer">Changes apply to this entry only. Manage future entries in Settings.</p>':''}<button type="button" class="text-btn" data-action="calc-key" data-id="C">Clear amount</button>${t?`<button class="btn danger full spacer" type="button" data-action="delete-transaction" data-id="${esc(t.id)}">Delete transaction</button>`:''}<button type="button" class="btn secondary full spacer" data-action="entry-done">Done</button></section></div>
    <div class="entry-footer"><p class="form-error" id="form-error" role="alert"></p><div class="segmented" id="transaction-types"><button type="button" class="${type==='expense'?'selected':''}" data-action="transaction-type" data-id="expense">Expenses</button><button type="button" class="${type==='income'?'selected':''}" data-action="transaction-type" data-id="income">Income</button></div><button class="btn full" type="submit">${t?'Save changes':'Add Transaction'}</button></div>
  </form>`);
  $('#editor').classList.add('transaction-editor');
  $('.dialog-head').innerHTML=`<button class="icon-btn" data-action="close" aria-label="Close dialog">×</button><h2 id="dialog-title">${t?'Edit transaction':'Add transaction'}</h2><button class="icon-btn" data-action="entry-options" aria-label="Transaction options" aria-expanded="false">···</button>`;
  transactionPanel(t?'keypad':'categories');
}
function readTemplate(){if(/[+×÷−*/()\-]|^\.|\.$/.test($('#amount').value))$('#amount').value=evaluateExpression($('#amount').value);const categoryId=$('#category-id').value;if(!categoryId)throw Error('Choose a category.');return {type:$('#transaction-type').value,amount:parseAmount($('#amount').value),categoryId,labelIds:[...document.querySelectorAll('#label-chips .chip.selected')].map(b=>b.dataset.id),description:$('#description').value.trim(),excluded:$('#excluded').checked};}
function saveTransaction(form){try{const template=readTemplate();const date=$('#transaction-date').value;if(!validDate(date))throw Error('Choose a valid date.');const id=form.dataset.id;const frequency=$('#frequency')?.value||'none';const ok=commit(next=>{let t=next.transactions.find(t=>t.id===id);if(t){Object.assign(t,template,{date});}else {t={id:uid(),...template,date};next.transactions.push(t);}if(frequency!=='none'){const rule={id:uid(),template,startDate:date,frequency,nextIndex:1,active:true,endDate:null};t.ruleId=rule.id;next.rules.push(rule);processRules(next);}});if(ok){closeDialog();toast('Transaction saved.');}}catch(e){error(e.message);}}
function budgetDialog(id){const b=id?state.budgets.find(b=>b.id===id):null;openDialog(b?'Edit monthly budget':'New monthly budget',`<form id="budget-form" data-id="${esc(id||'')}"><div class="notice">Budgets repeat every calendar month. The first period starts on your chosen date.</div><label class="field">Budget name<input id="budget-name" maxlength="80" value="${esc(b?.name||'')}" placeholder="e.g. Monthly essentials" required></label><label class="field">Monthly limit (SGD)<input id="budget-amount" inputmode="decimal" value="${b?(b.amount/100).toFixed(2):''}" placeholder="500.00" required></label><label class="field">Start date<input id="budget-start" type="date" min="1900-01-01" max="2200-12-31" value="${b?.startDate||month+'-01'}" required></label><label class="field">Included categories</label><p class="muted small spacer">Leave all unselected to include every expense category.</p><div class="chips" id="budget-categories">${state.categories.filter(c=>c.type==='expense'&&(!c.archived||b?.categoryIds.includes(c.id))).map(c=>`<button type="button" class="chip ${b?.categoryIds.includes(c.id)?'selected':''}" aria-pressed="${!!b?.categoryIds.includes(c.id)}" data-action="toggle-chip" data-id="${esc(c.id)}">${esc(c.icon)} ${esc(c.name)}</button>`).join('')}</div><p class="form-error" id="form-error" role="alert"></p><div class="btn-row">${b?`<button type="button" class="btn danger" data-action="delete-budget" data-id="${esc(id)}">Delete</button>`:''}<button class="btn" type="submit">Save budget</button></div></form>`);}
function manageCategories(){openDialog('Categories',`<button class="btn full secondary" data-action="new-category">+ Add category</button>${state.categories.map(c=>`<div class="manage-row ${c.archived?'archived':''}">${categoryIcon(c)}<div class="copy"><strong>${esc(c.name)}</strong><small>${c.type==='expense'?'Expense':'Income'}${c.archived?' · Archived':''}</small></div><button class="text-btn" data-action="edit-category" data-id="${esc(c.id)}">Edit</button><button class="text-btn" data-action="archive-category" data-id="${esc(c.id)}">${c.archived?'Restore':'Archive'}</button></div>`).join('')}<p class="muted small spacer">Archiving hides a category from new entries. Existing records stay intact.</p>`);}
function categoryDialog(id){const c=id?cat(id):null;openDialog(c?'Edit category':'New category',`<form id="category-form" data-id="${esc(id||'')}"><label class="field">Name<input id="category-name" maxlength="80" value="${esc(c?.name||'')}" required></label><div class="field-row"><label class="field">Icon or emoji<input id="category-icon" maxlength="20" value="${esc(c?.icon||'◈')}" required></label><label class="field">Colour<input id="category-color" type="color" value="${c?.color||'#2563eb'}"></label></div><label class="field">Type<select id="category-type" ${c?'disabled':''}><option value="expense">Expense</option><option value="income" ${c?.type==='income'?'selected':''}>Income</option></select></label><p class="form-error" id="form-error" role="alert"></p><div class="btn-row"><button class="btn" type="submit">Save category</button></div></form>`);}
function manageLabels(){openDialog('Labels',`<button class="btn secondary full" data-action="new-label">+ Add label</button>${state.labels.length?state.labels.map(l=>`<div class="manage-row"><div class="copy"><strong>${esc(l.name)}</strong></div><button class="text-btn" data-action="edit-label" data-id="${esc(l.id)}">Rename</button><button class="text-btn red" data-action="delete-label" data-id="${esc(l.id)}">Delete</button></div>`).join(''):empty('A little extra context','Use labels like Needs, Wants or Coffee to group transactions across categories.')}`);}
function labelDialog(id){const l=state.labels.find(l=>l.id===id);openDialog(l?'Rename label':'New label',`<form id="label-form" data-id="${esc(id||'')}"><label class="field">Label name<input id="label-name" maxlength="60" value="${esc(l?.name||'')}" required></label><p class="form-error" id="form-error" role="alert"></p><div class="btn-row"><button class="btn" type="submit">Save label</button></div></form>`);}
function manageRules(){openDialog('Recurring transactions',`<div class="notice">Due entries are added when you open the app. Pause a rule to stop future entries; existing transactions stay intact.</div>${state.rules.length?state.rules.map(r=>`<div class="manage-row">${categoryIcon(cat(r.template.categoryId))}<div class="copy"><strong>${esc(r.template.description||cat(r.template.categoryId).name)}</strong><small>${money(r.template.amount)} · ${FREQUENCIES[r.frequency]}<br>${r.active?'Next: '+dateLabel(occurrence(r,r.nextIndex)):'Paused'}</small></div><button class="text-btn" data-action="edit-rule" data-id="${esc(r.id)}">Edit</button><button class="text-btn" data-action="toggle-rule" data-id="${esc(r.id)}">${r.active?'Pause':'Resume'}</button></div>`).join(''):empty('No recurring entries','Set a repeat frequency when adding a transaction.','add','Add transaction')}`);}
function ruleDialog(id){const r=state.rules.find(r=>r.id===id);openDialog('Edit recurring transaction',`<form id="rule-form" data-id="${esc(id)}"><div class="notice">Changes apply to future entries. Existing transactions are preserved. Resuming adds any due entries since the last occurrence.</div><label class="field">Amount (SGD)<input id="rule-amount" inputmode="decimal" value="${(r.template.amount/100).toFixed(2)}" required></label><label class="field">Description<input id="rule-description" maxlength="1000" value="${esc(r.template.description)}"></label><label class="field">Repeat<select id="rule-frequency">${Object.entries(FREQUENCIES).filter(([k])=>k!=='none').map(([k,v])=>`<option value="${k}" ${r.frequency===k?'selected':''}>${v}</option>`).join('')}</select></label><label class="field">Next date<input id="rule-date" type="date" min="1900-01-01" max="2200-12-31" value="${occurrence(r,r.nextIndex)}" required></label><label class="field">End date (optional)<input id="rule-end" type="date" min="1900-01-01" max="2200-12-31" value="${r.endDate||''}"></label><p class="form-error" id="form-error" role="alert"></p><div class="btn-row"><button type="button" class="btn danger" data-action="remove-rule" data-id="${esc(id)}">Remove rule</button><button class="btn" type="submit">Save rule</button></div></form>`);}
function scheduledDialog(){const up=upcoming();openDialog('Scheduled · '+esc(monthLabel(month)),`${up.length?up.map(t=>`<div class="manage-row">${categoryIcon(cat(t.categoryId))}<div class="copy"><strong>${esc(t.description||cat(t.categoryId).name)}</strong><small>${dateLabel(t.date)} · ${t.type==='expense'?'−':'+'}${money(t.amount)}</small></div><button class="text-btn" data-action="${t.existing?'edit-transaction':'edit-rule'}" data-id="${esc(t.id)}">Edit</button></div>`).join(''):empty('Nothing scheduled','Upcoming transactions will appear here.')}<p class="muted small spacer">Upcoming entries are excluded from actual spending until their date arrives.</p>`);}
function download(content,name,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function backup(){if(blocked){try{download(localStorage.getItem(STORAGE_KEY)||'{}',`everyday-original-data-${today()}.json`,'application/json');}catch{toast('Browser storage is unavailable.');}}else download(JSON.stringify(state,null,2),`everyday-backup-${today()}.json`,'application/json');}
function calculator(){transactionPanel('keypad');}
function evaluateExpression(value){const s=value.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll(' ','');if(s.length>200||!/^[\d.+*/()\-]+$/.test(s))throw Error('Enter a valid calculation.');const tokens=s.match(/\d+(?:\.\d*)?|\.\d+|[+*/()\-]/g);if(!tokens||tokens.join('')!==s)throw Error('Enter a valid calculation.');let i=0;function atom(){if(tokens[i]==='-'){i++;return -atom();}if(tokens[i]==='+'){i++;return atom();}if(tokens[i]==='('){i++;const n=sum();if(tokens[i++]!==')')throw Error('Check your brackets.');return n;}const token=tokens[i++];if(!token||!/^(\d|\.)/.test(token))throw Error('Enter a valid calculation.');return Number(token);}function product(){let n=atom();while(['*','/'].includes(tokens[i])){const op=tokens[i++],rhs=atom();n=op==='*'?n*rhs:n/rhs;}return n;}function sum(){let n=product();while(['+','-'].includes(tokens[i])){const op=tokens[i++],rhs=product();n=op==='+'?n+rhs:n-rhs;}return n;}const result=sum();if(i!==tokens.length||!Number.isFinite(result)||result<=0)throw Error('The result must be a positive amount.');return result.toFixed(2);}

document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action,id=el.dataset.id;
  if(a==='close')closeDialog();
  else if(a==='add')transactionDialog();
  else if(a==='edit-transaction')transactionDialog(id);
  else if(a==='prev-month'||a==='next-month'){const next=shiftMonth(month,a==='prev-month'?-1:1);if(next>='1900-01'&&next<='2200-12'){month=next;render();}}
  else if(a==='toggle-filters'){showFilters=!showFilters;render();}
  else if(a==='clear-filters'){filter={query:'',type:'all',category:'all',label:'all',from:'',to:''};render();}
  else if(a==='overview-type'){overviewType=id;render();}
  else if(a==='toggle-chip'){el.classList.toggle('selected');el.setAttribute('aria-pressed',String(el.classList.contains('selected')));}
  else if(a==='select-category'){$('#category-id').value=id;$('#category-picker').innerHTML=categoryPicker($('#transaction-type').value,id);transactionPanel('keypad');}
  else if(a==='transaction-type'){$('#transaction-type').value=id;$('#category-id').value='';$('#category-picker').innerHTML=categoryPicker(id,'');document.querySelectorAll('#transaction-types button').forEach(b=>b.classList.toggle('selected',b.dataset.id===id));transactionPanel('categories');}
  else if(a==='quick-label'){const name=prompt('New label name');if(name?.trim()){const clean=name.trim().slice(0,60);let l=state.labels.find(l=>l.name.toLowerCase()===clean.toLowerCase());if(!l){l={id:uid(),name:clean};if(!commit(s=>s.labels.push(l)))return;}const selected=[...document.querySelectorAll('#label-chips .selected')].map(b=>b.dataset.id);$('#label-chips').outerHTML=labelChips([...selected,l.id]);}}
  else if(a==='calculator')calculator();
  else if(a==='choose-category'){transactionPanel($('#transaction-form').dataset.panel==='categories'&&$('#category-id').value?'keypad':'categories');}
  else if(a==='entry-options'){const expanded=$('#transaction-form').dataset.panel!=='options';transactionPanel(expanded?'options':$('#category-id').value?'keypad':'categories');el.setAttribute('aria-expanded',String(expanded));}
  else if(a==='entry-done'){transactionPanel($('#category-id').value?'keypad':'categories');$('[data-action="entry-options"]').setAttribute('aria-expanded','false');}
  else if(a==='calc-key'){const input=$('#amount');if(id==='C')input.value='';else if(id==='⌫')input.value=input.value.slice(0,-1);else if(id==='='){try{input.value=evaluateExpression(input.value);parseAmount(input.value);$('#form-error').textContent='';}catch(err){error(err.message);}}else if(input.value.length<100){input.value+=id;}input.scrollLeft=input.scrollWidth;}
  else if(a==='delete-transaction'){if(confirm('Delete this transaction? A deleted recurring occurrence will not be added again.')){if(commit(s=>{s.transactions=s.transactions.filter(t=>t.id!==id);})){closeDialog();toast('Transaction deleted.');}}}
  else if(a==='add-budget')budgetDialog();
  else if(a==='edit-budget')budgetDialog(id);
  else if(a==='delete-budget'){if(confirm('Delete this budget? Your transactions will stay.')){if(commit(s=>{s.budgets=s.budgets.filter(b=>b.id!==id);})){closeDialog();toast('Budget deleted.');}}}
  else if(a==='manage-categories')manageCategories();
  else if(a==='new-category')categoryDialog();
  else if(a==='edit-category')categoryDialog(id);
  else if(a==='archive-category'){if(commit(s=>{const c=s.categories.find(c=>c.id===id);c.archived=!c.archived;}))manageCategories();}
  else if(a==='manage-labels')manageLabels();
  else if(a==='new-label')labelDialog();
  else if(a==='edit-label')labelDialog(id);
  else if(a==='delete-label'){if(confirm('Delete this label from all transactions and recurring rules?')){if(commit(s=>{s.labels=s.labels.filter(l=>l.id!==id);for(const t of [...s.transactions,...s.rules.map(r=>r.template)])t.labelIds=t.labelIds.filter(x=>x!==id);})){manageLabels();}}}
  else if(a==='manage-rules')manageRules();
  else if(a==='edit-rule')ruleDialog(id);
  else if(a==='toggle-rule'){if(commit(s=>{const r=s.rules.find(r=>r.id===id);r.active=!r.active;processRules(s);})){manageRules();}}
  else if(a==='remove-rule'){if(confirm('Remove this recurring rule? Existing transactions will stay.')){if(commit(s=>{s.rules=s.rules.filter(r=>r.id!==id);s.transactions.forEach(t=>{if(t.ruleId===id)delete t.ruleId;});})){manageRules();}}}
  else if(a==='scheduled')scheduledDialog();
  else if(a==='export-filtered'){download(transactionsCsv(state,historyRows()),`everyday-transactions-${month}.csv`,'text/csv;charset=utf-8');toast('CSV downloaded.');}
  else if(a==='export-all'){download(transactionsCsv(state),`everyday-all-transactions-${today()}.csv`,'text/csv;charset=utf-8');toast('CSV downloaded.');}
  else if(a==='backup'){backup();toast('Backup downloaded.');}
  else if(a==='restore')$('#restore-file').click();
  else if(a==='reset'){if(confirm('Delete all data in this browser? Download a backup first. This cannot be undone.')){try{const fresh=initialState();saveState(fresh);state=fresh;blocked=false;applyTheme();render();toast('Data reset.');}catch{toast('Browser storage is unavailable.');}}}
});
document.addEventListener('submit',e=>{const form=e.target;if(!form.id.endsWith('-form'))return;e.preventDefault();
  if(form.id==='transaction-form'){saveTransaction(form);return;}
  try{
    if(form.id==='budget-form'){const name=$('#budget-name').value.trim(),amount=parseAmount($('#budget-amount').value),startDate=$('#budget-start').value;if(!name)throw Error('Enter a budget name.');if(!validDate(startDate))throw Error('Choose a valid start date.');const b={id:form.dataset.id||uid(),name,amount,startDate,categoryIds:[...document.querySelectorAll('#budget-categories .selected')].map(x=>x.dataset.id)};if(commit(s=>{const i=s.budgets.findIndex(x=>x.id===b.id);i<0?s.budgets.push(b):s.budgets.splice(i,1,b);})){closeDialog();toast('Budget saved.');}}
    else if(form.id==='category-form'){const name=$('#category-name').value.trim(),icon=$('#category-icon').value.trim();if(!name||!icon)throw Error('Enter a name and icon.');const type=$('#category-type').value;if(state.categories.some(c=>c.id!==form.dataset.id&&c.type===type&&c.name.toLowerCase()===name.toLowerCase()))throw Error('That category name already exists.');const c={id:form.dataset.id||uid(),name,icon,color:$('#category-color').value,type,archived:cat(form.dataset.id)?.archived||false};if(commit(s=>{const i=s.categories.findIndex(x=>x.id===c.id);i<0?s.categories.push(c):s.categories.splice(i,1,c);})){manageCategories();toast('Category saved.');}}
    else if(form.id==='label-form'){const name=$('#label-name').value.trim();if(!name)throw Error('Enter a label name.');if(state.labels.some(l=>l.id!==form.dataset.id&&l.name.toLowerCase()===name.toLowerCase()))throw Error('That label already exists.');const l={id:form.dataset.id||uid(),name};if(commit(s=>{const i=s.labels.findIndex(x=>x.id===l.id);i<0?s.labels.push(l):s.labels.splice(i,1,l);})){manageLabels();toast('Label saved.');}}
    else if(form.id==='rule-form'){const amount=parseAmount($('#rule-amount').value),startDate=$('#rule-date').value,endDate=$('#rule-end').value||null,frequency=$('#rule-frequency').value,description=$('#rule-description').value.trim();if(!validDate(startDate)||endDate&&(!validDate(endDate)||endDate<startDate))throw Error('Choose valid next and end dates.');if(commit(s=>{const r=s.rules.find(r=>r.id===form.dataset.id);Object.assign(r,{startDate,endDate,frequency,nextIndex:0});Object.assign(r.template,{amount,description});processRules(s);})){manageRules();toast('Recurring rule saved.');}}
  }catch(err){error(err.message);}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){filter.query=e.target.value;$('#history').innerHTML=historyHtml();}});
document.addEventListener('change',e=>{const id=e.target.id,value=e.target.value;if(id==='month'){if(/^\d{4}-\d{2}$/.test(value)&&value>='1900-01'&&value<='2200-12'){month=value;render();}}else if(id.startsWith('filter-')){filter[id.slice(7)]=value;if(filter.from&&filter.to&&filter.from>filter.to){toast('The start date must be before the end date.');}render();}else if(id==='period'){period=value;render();}else if(id==='chart-mode'){chartMode=value;render();}else if(id==='theme')commit(s=>s.settings.theme=value);});
$('#restore-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>10000000){toast('Backup must be smaller than 10 MB.');return;}try{const candidate=validateState(JSON.parse(await file.text()));if(!confirm(`Replace current data with this backup (${candidate.transactions.length} transactions)? This cannot be undone. Download your current backup first.`))return;processRules(candidate);saveState(candidate);state=candidate;blocked=false;filter={query:'',type:'all',category:'all',label:'all',from:'',to:''};applyTheme();render();toast('Backup restored.');}catch(err){toast('Could not restore: '+err.message);}});
$('#add-transaction').addEventListener('click',()=>transactionDialog());
$('#editor').addEventListener('click',e=>{if(e.target===$('#editor')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY){try{state=loadState();blocked=false;applyTheme();render();if($('#editor').open)closeDialog();toast('Updated from another tab.');}catch{blocked=true;render();}}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){catchUp();render();}});
matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>applyTheme());
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
